name: project_akhir_pam_lanjut_115
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  flutter_secure_storage: ^9.0.0
  http: ^0.13.6
  intl: ^0.19.0
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/promo.jpg
    - assets/images/diskon.jpg
    - assets/images/kapal.jpg
    - assets/images/travel1.jpg
    - assets/images/pesawat1.jpg
    - assets/images/kereta1.jpg
